name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  packages: read

jobs:
  ci:
    uses: matt-riley/matt-riley-ci/.github/workflows/ci.yml@bcaf4ae43edf7d26421741424b82c842c83e55ce # v2
    with:
      build: true
      test: true
      vet: true
      fmt: true
      lint: true
      concurrency-suffix: ci

  govulncheck:
    needs: ci
    if: ${{ always() }}
    uses: matt-riley/matt-riley-ci/.github/workflows/go-security.yml@bcaf4ae43edf7d26421741424b82c842c83e55ce # v2
    with:
      go-version-file: cli/go.mod
      working-directory: cli
      concurrency-suffix: security
